#[cfg(test)]
mod tests {

    #[test]
    fn test_ffi_rust_call_c_cpp() {
        use comprehensive_rust::ffi_interner;
        use std::ffi::CString;
        unsafe {
            // 1. 创建 interner
            let interner = ffi_interner::interner_new();
            assert!(!interner.is_null());

            // 2. 准备字符串
            let s1 = CString::new("hello").unwrap();
            let s2 = CString::new("world").unwrap();
            let s3 = CString::new("hello").unwrap();

            // 3. 插入并获取指针
            let p1 = ffi_interner::interner_intern(interner, s1.as_ptr());
            let p2 = ffi_interner::interner_intern(interner, s2.as_ptr());
            let p3 = ffi_interner::interner_intern(interner, s3.as_ptr());

            assert!(!p1.is_null());
            assert!(!p2.is_null());
            assert!(!p3.is_null());

            // 相同字符串应返回相同指针（池化）
            assert_eq!(p1, p3);
            // 不同字符串应不同指针
            assert_ne!(p1, p2);

            // 4. 验证计数
            assert_eq!(ffi_interner::interner_count(interner), 2);

            // 5. 释放资源
            ffi_interner::interner_free(interner);
        }
    }

    #[test]
    fn test_rust_call_c() {
        use comprehensive_rust::ffi_text_analysis;
        use std::ffi::{CStr, CString};
        use std::os::raw::c_void;
        use std::ptr;

        // 回调函数必须与 C 期望的签名一致，标记为 unsafe extern "C"
        unsafe extern "C" fn count_tokens(
            _user_context: *mut c_void,
            token: *mut ffi_text_analysis::Token,
            _result: *mut c_void,
        ) -> bool {
            unsafe {
                let tok = &*token;
                let slice = CStr::from_ptr(tok.start).to_bytes();
                let text = String::from_utf8_lossy(slice);
                println!(
                    "Token: '{}' at index {}, length {}",
                    text, tok.index, tok.length
                );
            }
            true
        }

        unsafe {
            let ta = ffi_text_analysis::ta_new();
            assert!(!ta.is_null());

            let text = "Hello, world! This is a test.";
            let c_text = CString::new(text).unwrap();
            let err = ffi_text_analysis::ta_set_text(ta, c_text.as_ptr(), text.len(), true);
            assert_eq!(err, ffi_text_analysis::TAError::Ok);

            // 显式指定类型为 ffi::TokenCallback
            let callback: ffi_text_analysis::TokenCallback = Some(count_tokens);
            let count =
                ffi_text_analysis::ta_foreach_token(ta, &callback as *const _, ptr::null_mut());
            println!("Total tokens: {}", count);

            ffi_text_analysis::ta_free(ta);
        }
    }

    #[test]
    fn test_c_rand() {
        use libc::{rand, srand};

        // unsafe extern "C" {
        //     /// Seed the rng
        //     fn srand(seed: std::ffi::c_uint);
        //
        //     fn rand() -> std::ffi::c_int;
        // }

        use std::time::SystemTime;

        let seed = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap()
            .as_secs() as u32;

        unsafe { srand(seed) };

        let a = unsafe { rand() as i32 };
        println!("{a:?}");
    }

    #[test]
    fn test_c_abs() {
        use std::ffi::c_int;

        unsafe extern "C" {
            safe fn abs(x: c_int) -> c_int;
        }

        let x = -42;
        let abs_x = abs(x);
        println!("{x}, {abs_x}");
    }

    #[test]
    fn test_diff_semantic() {
        use std::ffi::{c_char, CStr};
        use std::time::{SystemTime, SystemTimeError, UNIX_EPOCH};

        unsafe extern "C" {
            /// Create a formatted time based on timestamp `t`.
            fn ctime(t: *const libc::time_t) -> *const c_char;
        }

        fn now_formatted() -> Result<String, SystemTimeError> {
            let now = SystemTime::now().duration_since(UNIX_EPOCH)?;
            let seconds = now.as_secs() as i64;
            print!("{seconds}");

            // SAFETY: `seconds` is generated by the system clock and will not cause
            // overflow
            let ptr = unsafe { ctime(&seconds) };

            // SAFETY: ctime returns a pointer to a preallocated (non-null) buffer
            let ptr = unsafe { CStr::from_ptr(ptr) };

            // SAFETY: ctime uses valid UTF-8
            let fmt = ptr.to_str().unwrap();

            Ok(fmt.trim_end().to_string())
        }

        let t = now_formatted();
        println!("{t:?}");
    }

    #[test]
    fn test() {
        let c_repr = b"Hello, C\0";
        let cc_repr = (b"Hello, C++\0", 10u32);
        let rust_repr = (b"Hello, Rust", 11);

        // C representation to Rust
        unsafe {
            let ptr = c_repr.as_ptr() as *const i8;
            let c: &str = std::ffi::CStr::from_ptr(ptr).to_str().unwrap();
            println!("{c}");
        };

        // C++ representation to Rust
        unsafe {
            let ptr = cc_repr.0.as_ptr();
            let bytes = std::slice::from_raw_parts(ptr, cc_repr.1 as usize);
            let cc: &str = std::str::from_utf8_unchecked(bytes);
            println!("{cc}");
        };

        // Rust representation (bytes) to string slice
        unsafe {
            let ptr = rust_repr.0.as_ptr();
            let bytes = std::slice::from_raw_parts(ptr, rust_repr.1);
            let rust: &str = std::str::from_utf8_unchecked(bytes);
            println!("{rust}");
        };
    }
}
